"""
This type stub file was generated by pyright.
"""

from typing import List

def initial_generation(size: int) -> List[int]:
    ...

def patterns(pattern_number: int) -> dict[int, int]:
    ...

def rule_from_patterns(patterns: dict[int, int]) -> int:
    ...

def next_generation(current_generation: List[int], patterns: dict[int, int]) -> List[int]:
    ...

def generations(initial_pattern: List[int], patterns: dict[int, int], generations: int) -> List[List[int]]:
    ...

